export const LEARN_LESSONS = [
  {
    id: 1,
    title: 'Home Row — Left Hand',
    description: 'Master the foundation: A, S, D, F keys with your left hand fingers.',
    keys: ['a', 's', 'd', 'f'],
    blind: false,
    words: ['aaa', 'sss', 'ddd', 'fff', 'asdf', 'fdsa', 'as', 'sad', 'fad', 'add', 'dad', 'ads'],
  },
  {
    id: 2,
    title: 'Home Row — Right Hand',
    description: 'Master J, K, L, ; keys with your right hand fingers.',
    keys: ['j', 'k', 'l', ';'],
    blind: false,
    words: ['jjj', 'kkk', 'lll', 'jkl', 'lkj', 'jk', 'kl', 'lj'],
  },
  {
    id: 3,
    title: 'Full Home Row',
    description: 'Combine both hands across the entire home row.',
    keys: ['a', 's', 'd', 'f', 'j', 'k', 'l', ';'],
    blind: false,
    words: ['flask', 'glad', 'fall', 'lads', 'asks', 'dask', 'jads', 'alk', 'alf', 'salad', 'flask'],
  },
  {
    id: 4,
    title: 'Top Row — Left (Q, W, E, R, T)',
    description: 'Reach up with your left hand to the top row keys.',
    keys: ['q', 'w', 'e', 'r', 't'],
    blind: false,
    words: ['we', 'wet', 'tree', 'true', 'rest', 'test', 'were', 'where', 'there', 'quest', 'quite'],
  },
  {
    id: 5,
    title: 'Top Row — Right (Y, U, I, O, P)',
    description: 'Reach up with your right hand to the top row keys.',
    keys: ['y', 'u', 'i', 'o', 'p'],
    blind: false,
    words: ['you', 'your', 'pour', 'pout', 'yip', 'oily', 'poky', 'opus', 'polo', 'upon', 'input'],
  },
  {
    id: 6,
    title: 'Bottom Row — Left (Z, X, C, V, B)',
    description: 'Reach down with your left hand to the bottom row.',
    keys: ['z', 'x', 'c', 'v', 'b'],
    blind: false,
    words: ['cab', 'cabs', 'vex', 'box', 'zap', 'zebra', 'exact', 'exceed', 'vacuum', 'cable', 'crabs'],
  },
  {
    id: 7,
    title: 'Bottom Row — Right (N, M)',
    description: 'Reach down with your right hand to the bottom row.',
    keys: ['n', 'm'],
    blind: false,
    words: ['man', 'men', 'main', 'moon', 'name', 'mine', 'mean', 'monk', 'norm', 'menu', 'mango'],
  },
  {
    id: 8,
    title: 'Blind Home Row',
    description: 'Now type the home row WITHOUT looking at the keyboard. Build true muscle memory!',
    keys: ['a', 's', 'd', 'f', 'j', 'k', 'l'],
    blind: true,
    words: ['falls', 'flask', 'deals', 'flasks', 'salads', 'dads', 'asks', 'slap', 'lads', 'dark', 'flash'],
  },
  {
    id: 9,
    title: 'Blind Full Keyboard',
    description: 'The ultimate test — type common words without any on-screen keyboard guide.',
    keys: [],
    blind: true,
    words: ['practice', 'keyboard', 'fingers', 'typing', 'master', 'perfect', 'speed', 'accuracy', 'position', 'control'],
  },
  {
    id: 10,
    title: 'Numbers Row',
    description: 'Learn to reach the number keys efficiently.',
    keys: ['1', '2', '3', '4', '5', '6', '7', '8', '9', '0'],
    blind: false,
    words: ['123', '456', '789', '100', '2024', '3.14', '99%', '1000', '42', '007'],
  },
];

export const FINGER_MAP: Record<string, { finger: string; color: string; hand: 'left' | 'right' }> = {
  '1': { finger: 'pinky', color: '#ff3d6b', hand: 'left' },
  '2': { finger: 'ring', color: '#ff8c00', hand: 'left' },
  '3': { finger: 'middle', color: '#ffd700', hand: 'left' },
  '4': { finger: 'index', color: '#00ff88', hand: 'left' },
  '5': { finger: 'index', color: '#00ff88', hand: 'left' },
  '6': { finger: 'index', color: '#00f5ff', hand: 'right' },
  '7': { finger: 'index', color: '#00f5ff', hand: 'right' },
  '8': { finger: 'middle', color: '#b847ff', hand: 'right' },
  '9': { finger: 'ring', color: '#ff8c00', hand: 'right' },
  '0': { finger: 'pinky', color: '#ff3d6b', hand: 'right' },
  q: { finger: 'pinky', color: '#ff3d6b', hand: 'left' },
  w: { finger: 'ring', color: '#ff8c00', hand: 'left' },
  e: { finger: 'middle', color: '#ffd700', hand: 'left' },
  r: { finger: 'index', color: '#00ff88', hand: 'left' },
  t: { finger: 'index', color: '#00ff88', hand: 'left' },
  y: { finger: 'index', color: '#00f5ff', hand: 'right' },
  u: { finger: 'index', color: '#00f5ff', hand: 'right' },
  i: { finger: 'middle', color: '#b847ff', hand: 'right' },
  o: { finger: 'ring', color: '#ff8c00', hand: 'right' },
  p: { finger: 'pinky', color: '#ff3d6b', hand: 'right' },
  a: { finger: 'pinky', color: '#ff3d6b', hand: 'left' },
  s: { finger: 'ring', color: '#ff8c00', hand: 'left' },
  d: { finger: 'middle', color: '#ffd700', hand: 'left' },
  f: { finger: 'index', color: '#00ff88', hand: 'left' },
  g: { finger: 'index', color: '#00ff88', hand: 'left' },
  h: { finger: 'index', color: '#00f5ff', hand: 'right' },
  j: { finger: 'index', color: '#00f5ff', hand: 'right' },
  k: { finger: 'middle', color: '#b847ff', hand: 'right' },
  l: { finger: 'ring', color: '#ff8c00', hand: 'right' },
  ';': { finger: 'pinky', color: '#ff3d6b', hand: 'right' },
  z: { finger: 'pinky', color: '#ff3d6b', hand: 'left' },
  x: { finger: 'ring', color: '#ff8c00', hand: 'left' },
  c: { finger: 'middle', color: '#ffd700', hand: 'left' },
  v: { finger: 'index', color: '#00ff88', hand: 'left' },
  b: { finger: 'index', color: '#00ff88', hand: 'left' },
  n: { finger: 'index', color: '#00f5ff', hand: 'right' },
  m: { finger: 'index', color: '#00f5ff', hand: 'right' },
  ',': { finger: 'middle', color: '#b847ff', hand: 'right' },
  '.': { finger: 'ring', color: '#ff8c00', hand: 'right' },
  '/': { finger: 'pinky', color: '#ff3d6b', hand: 'right' },
};

export const FINGER_COLORS = {
  pinky: '#ff3d6b',
  ring: '#ff8c00',
  middle: '#ffd700',
  index: '#00ff88',
  thumb: '#00f5ff',
};
